name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Cache de dependências
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Construir imagem Docker
        run: docker build -t iscool-gpt .

      - name: Rodar testes dentro do container
        run: docker run --rm \
              -e NODE_ENV=test \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
              iscool-gpt npm test
